package com.imageworks.migration

/**
 * This file contains all the case classes and case objects that act
 * as options to customize the SQL generated by the Migration methods.
 *
 * The design uses the Scala compiler to only allow valid options to
 * be passed to a Migration method.  Some case classes may be used by
 * multiple methods and since the base trait for the method's option
 * type may be sealed, they all need to be defined in a single source
 * file.
 */

/**
 * The base trait for all column options.  This is not a sealed class
 * so database specific column options can be defined.
 */
trait ColumnOption

/**
 * The base trait for all foreign key options.
 */
sealed trait ForeignKeyOption

/**
 * The base trait for all index options.
 */
sealed trait IndexOption

/**
 * The base trait for all table options.
 */
sealed trait TableOption

/**
 * A default value for a column.
 */
case class Default(value : String)
  extends ColumnOption

/**
 * A limit on the size of a column type.
 */
case class Limit(length : Int)
  extends ColumnOption
{
  if (length < 0) {
    val message = "The limit in " +
                  this +
                  " must be greater than or equal to one."
    throw new IllegalArgumentException(message)
  }
}

/**
 * A name overriding the default index or foreign key constrant name
 * generated by Migration.
 */
case class Name(name : String)
  extends ForeignKeyOption
  with IndexOption
{
  if (name eq null) {
    throw new IllegalArgumentException("The name cannot be null.")
  }

  if (name.isEmpty) {
    throw new IllegalArgumentException("The name cannot be empty.")
  }
}

/**
 * Specify that the column's values must not be NULL.
 */
case object NotNull
  extends ColumnOption

/**
 * Specify that the column's values may be NULL.
 */
case object Nullable
  extends ColumnOption

/**
 * Specify the action that occurs when a value referenced in a foreign
 * key constraint is deleted.
 */
case class OnDelete(action : ForeignKeyConstraintAction)
  extends ForeignKeyOption

/**
 * Specify the action that occurs when a value referenced in a foreign
 * key constraint is updated.
 */
case class OnUpdate(action : ForeignKeyConstraintAction)
  extends ForeignKeyOption

/**
 * Specify that the column is a primary key.
 */
case object PrimaryKey
  extends ColumnOption

/**
 * Specify that the index on the requires that all the values indexed
 * are unique.
 */
case object Unique
  extends ColumnOption
  with IndexOption

/**
 * This class is defined to prevent ant from recompiling this source
 * file.
 */
private
class Options
